import {adminUser,ensureAdmin} from '@/lib/server/admin';
import {listLeads,history,db} from '@/lib/server/leads';
export const dynamic='force-dynamic';
export const metadata={title:'Lead inbox | Bondtite',robots:{index:false,follow:false}};
const statuses=['new','contacted','qualified','closed'];
export default async function LeadInbox({searchParams}:{searchParams:Promise<{q?:string;status?:string;error?:string;page?:string;due?:string}>}){
  const params=await searchParams,actor=await adminUser();
  if(!actor){const configured=ensureAdmin();return <main id="main-content" tabIndex={-1} className="lead-admin"><span className="mono">Bondtite admin</span><h1>Lead inbox</h1>{configured?<form action="/api/admin/login" method="post"><label>Username<input name="username" required autoComplete="username" defaultValue={process.env.NODE_ENV==='development'?'admin':''}/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="button button--primary">Sign in</button>{params.error&&<p role="alert">Username or password not recognised.</p>}</form>:<p>Create an administrator account using the server setup command.</p>}</main>;}
  const q=typeof params.q==='string'?params.q.slice(0,100):'',status=statuses.includes(params.status||'')?params.status!:'',due=params.due==='1';
  const pageNumber=Number(params.page),result=listLeads(q,status,Number.isSafeInteger(pageNumber)?pageNumber:1,25,due);
  const accounts=db().prepare('SELECT username FROM admins WHERE disabled=0 ORDER BY username').all();
  const query=new URLSearchParams({q,status,...(due?{due:'1'}:{})});
  return <main id="main-content" tabIndex={-1} className="lead-admin"><header><div><span className="mono">Bondtite admin · {actor}</span><h1>Lead inbox</h1><p>Enquiries, dealer interest and document requests.</p></div><form action="/api/admin/logout" method="post"><button>Sign out</button></form></header>
    <form className="lead-admin__filters"><label>Search<input name="q" defaultValue={q} placeholder="Name, phone, email or message"/></label><label>Status<select name="status" defaultValue={status}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Follow-up<select name="due" defaultValue={due?'1':''}><option value="">All dates</option><option value="1">Due today or overdue (UTC)</option></select></label><button className="button button--primary">Filter</button></form>
    <div className="lead-admin__toolbar"><p>{result.total} leads · Page {result.page} of {result.pages}</p><a href={`/api/admin/leads/export?${query}`}>Export filtered CSV</a></div>
    {result.total===0&&<p>No leads match these filters.</p>}
    {result.leads.map(lead=><article key={lead.id}><header><h2>{lead.name}</h2><span>Received {new Date(lead.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</span></header><dl className="lead-admin__origin"><div><dt>Enquiry type</dt><dd>{lead.source==='tds'?'Document request':lead.source==='dealer'?'Dealer enquiry':'Contact enquiry'}</dd></div><div><dt>Form</dt><dd>{lead.form_name || (lead.source==='tds'?'TDS download form':'Contact form')}</dd></div><div><dt>Submitted from</dt><dd>{lead.source_page?<a href={lead.source_page} target="_blank" rel="noopener noreferrer">{lead.source_page}</a>:'Not recorded for this lead'}</dd></div></dl><p>{lead.topic} · {lead.product||'Product not specified'}</p><p><a href={`tel:${lead.mobile}`}>{lead.mobile}</a>{lead.email&&<> · <a href={`mailto:${lead.email}`}>{lead.email}</a></>} · {lead.city} {lead.role}</p><p className="lead-admin__message">{lead.message}</p><small>Reference: {lead.id}</small>
      <form action="/api/admin/leads" method="post"><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="version" value={lead.version}/><label>Status<select name="status" defaultValue={lead.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Assigned to<select name="assignee" defaultValue={lead.assignee}><option value="">Unassigned</option>{accounts.map(a=><option key={String(a.username)}>{String(a.username)}</option>)}</select></label><label>Follow-up date (UTC)<input name="follow_up" type="date" defaultValue={lead.follow_up}/></label><label>Internal notes<textarea name="notes" maxLength={4000} defaultValue={lead.notes}/></label><button className="button button--primary">Save update</button></form>
      <details><summary>Activity history</summary><ul>{history(lead.id).map((entry,i)=><li key={i}>{new Date(entry.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · {entry.actor} · {entry.action}{entry.detail&&<small className="lead-admin__audit">{entry.detail}</small>}</li>)}</ul></details>
    </article>)}
    <nav className="lead-admin__toolbar" aria-label="Lead pages">{result.page>1&&<a href={`?${query}&page=${result.page-1}`}>Previous page</a>}{result.page<result.pages&&<a href={`?${query}&page=${result.page+1}`}>Next page</a>}</nav>
  </main>;
}
