export type Policy = { title: string; summary: string; sections: { id: string; title: string; paragraphs: string[] }[] };
export const policies: Record<string, Policy> = {
  'privacy-policy': {
    title: 'Privacy Policy',
    summary: 'How this Bondtite website collects and uses your information when you ask for help, make an enquiry or download a technical document.',
    sections: [
      { id: 'scope', title: 'About this notice', paragraphs: ['This notice covers information submitted through this Bondtite website, an Astral adhesives brand. It covers product and dealer enquiries, technical support and technical data sheet requests. Other Astral websites have their own privacy notices.'] },
      { id: 'information', title: 'Information we collect', paragraphs: ['Enquiry forms collect your name, mobile number, enquiry type and project or application details. You may also provide your email address, city, user type and product interest. Dealer enquiries use the same contact process.', 'Technical data sheet requests collect your name, mobile number, requested product and consent. Submission records also include the date and time, form name and originating page, so the team can understand your request.', 'The Product Advisor uses your choices to display guidance. These choices are not saved as a lead just by using the advisor. If you continue to the contact form, your project summary is carried into that form and is stored when you submit it.', 'Operational records help prevent repeated submissions, abuse and unauthorised access. They can include submission references, administrative activity and hashed rate-limit identifiers derived from a phone number or, where configured, a network address. Please do not submit payment information, passwords or sensitive personal documents in an enquiry.'] },
      { id: 'use', title: 'Why we use your information', paragraphs: ['We use submitted information to respond to your request, provide requested documents, understand your application, manage dealer enquiries and keep a record of relevant follow-up. Required fields allow us to process and respond to the request.', 'Your form consent relates to processing that request and contacting you about it. It is not a separate subscription to advertising messages. The website does not process online purchases or payments.'] },
      { id: 'access', title: 'Access and protection', paragraphs: ['Enquiry records are stored in the website’s lead system, with access restricted through administrator authentication and authorised database access. Relevant team members use the records to handle enquiries and support.', 'Hosting and technical service providers may process information to operate, maintain and protect the service. Information may also need to be disclosed where required by applicable law. Access controls and operational safeguards reduce risk, but no internet service can guarantee absolute security.'] },
      { id: 'retention', title: 'Keeping your information', paragraphs: ['Submitted enquiries remain in the lead system for follow-up and record keeping; the current system does not automatically delete lead records after a fixed interval. Operational and backup copies may also exist. You can contact the team to ask about retention or request deletion of a particular submission. Legal or legitimate record-keeping requirements may affect what can be removed.'] },
      { id: 'choices', title: 'Your choices and requests', paragraphs: ['You can ask to access, correct or delete information you submitted, or withdraw consent to further enquiry follow-up. Contact customercare@astraladhesives.com with the subject “Bondtite privacy request” and enough information to identify your enquiry. The team may need to verify your identity before changing or disclosing records.', 'Withdrawing consent does not undo processing already completed. Requests are handled subject to applicable law and any necessary retention obligations. Do not send identity documents unless the team requests them through an appropriate channel.'] },
      { id: 'links', title: 'Cookies and external links', paragraphs: ['The Cookie Policy explains the browser storage used by this website. Links to Astral or other external websites take you to services governed by their own notices.'] },
      { id: 'updates', title: 'Changes and contact', paragraphs: ['This notice may be updated when the website or its information practices change. The date above identifies the latest revision. For questions, contact Astral Adhesives customer care using the details below.'] }
    ]
  },
  'cookie-policy': {
    title: 'Cookie Policy',
    summary: 'A straightforward explanation of cookies and browser storage used by this website.',
    sections: [
      { id: 'what', title: 'What cookies do', paragraphs: ['Cookies are small pieces of information a website stores in your browser. They can support functions such as maintaining a signed-in session. Browser memory, local storage and session storage are other ways a website can retain information.'] },
      { id: 'current-use', title: 'What this website currently uses', paragraphs: ['The public website currently has no configured analytics, advertising or cross-site tracking cookies. Browsing products, using the Product Advisor and submitting a public enquiry do not require an administrator login cookie.', 'The Product Advisor stores your selected task, materials and setting in session storage under “bondtite-advisor”, so you can return from a product without starting again. This contains no contact details and lasts for the browser tab’s session. Choose “Change task” to reset your choices. Product filters remain in page memory.'] },
      { id: 'admin', title: 'Essential administrator cookie', paragraphs: ['The first-party cookie “bondtite_admin” is set only after a successful administrator login. It contains a session token used to protect access to the lead inbox, rather than the submitted lead details.', 'The cookie expires after eight hours and is cleared on logout. It is HTTP-only, uses SameSite Strict and is marked Secure in production. Blocking it prevents administrator sign-in; ordinary product browsing does not depend on it.'] },
      { id: 'controls', title: 'Your browser controls', paragraphs: ['You can inspect, block or delete cookies in your browser’s privacy settings. Clearing cookies signs an administrator out. It does not delete enquiry records already saved on the server; contact the team for requests about those records.', 'There are currently no optional tracking categories to accept or reject, so this site does not display an optional-cookie consent banner. If optional tracking is introduced, the notice and relevant choice controls need to be updated before it is enabled.'] },
      { id: 'third-parties', title: 'Other websites', paragraphs: ['External links, including links to Astral Adhesives, open websites with their own cookie practices. This policy covers the Bondtite website, not the browser storage set by those services after you visit them.'] },
      { id: 'contact', title: 'Questions and updates', paragraphs: ['The revision date above shows when this policy was last updated. For questions about cookies or your information, contact customercare@astraladhesives.com.'] }
    ]
  },
  'terms-and-conditions': {
    title: 'Terms & Conditions',
    summary: 'The terms for browsing this website, using its product guidance and submitting enquiries.',
    sections: [
      { id: 'website', title: 'Using this website', paragraphs: ['This Bondtite website provides information about adhesives, their applications and ways to contact the team. Please use it lawfully and read these terms alongside the Privacy Policy and Cookie Policy. If you submit an enquiry for an organisation, you should have authority to provide its information.'] },
      { id: 'guidance', title: 'Product information and advice', paragraphs: ['Descriptions, images, application guides and Product Advisor results help you explore the range. Suitability depends on the specific substrates, surface preparation, working conditions and intended use.', 'Refer to the current official technical data sheet, safety data sheet, product label and instructions for the relevant product. Where a website summary differs from current official product documentation, use that documentation and contact the technical team for clarification.', 'Pack illustrations, available sizes and product availability may change. Website content does not create a product warranty or replace an applicable written warranty supplied with a product.'] },
      { id: 'enquiries', title: 'Enquiries and document downloads', paragraphs: ['Provide accurate contact details and information you are entitled to share. A successful form submission records an enquiry or document request; it does not confirm a purchase, quotation, dealership, supply commitment or service agreement.', 'A TDS form submission requests a document download. Browser settings and connectivity can affect delivery. Use the download link or contact the team if the file does not arrive. There is no online checkout or payment service on this website.'] },
      { id: 'ownership', title: 'Content and brand ownership', paragraphs: ['Brand names, logos, product images, documents and other content belong to their respective owners or licensors. You may consult the site and use downloaded product guidance for product evaluation and application reference.', 'Do not misrepresent affiliation, alter technical documents or reproduce protected content for commercial distribution without the appropriate permission, except where permitted by law.'] },
      { id: 'acceptable-use', title: 'Responsible use', paragraphs: ['Do not submit unlawful or misleading material, impersonate someone else, attempt unauthorised access to the lead system, introduce malicious code or interfere with the website’s operation. Protective measures may restrict abusive or unauthorised requests.'] },
      { id: 'availability', title: 'Availability and external services', paragraphs: ['The website may be updated or temporarily unavailable for maintenance or technical reasons. We aim to keep information useful and current, but do not promise uninterrupted access or that every summary is free of error.', 'External links are provided for reference. Their content and services are governed by their own terms and are not controlled by this website.'] },
      { id: 'rights', title: 'Your rights and applicable law', paragraphs: ['These terms do not exclude rights or remedies that cannot lawfully be excluded. Any product transaction remains subject to its applicable sale terms, warranty and statutory rights.', 'Use of this website is subject to applicable Indian law. Questions about a particular purchase, warranty or dispute should be directed to the team using the relevant transaction details.'] },
      { id: 'changes', title: 'Updates and questions', paragraphs: ['Revisions will be published on this page with an updated date. For questions about these terms, product information or website access, contact customercare@astraladhesives.com.'] }
    ]
  }
};
