import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
const directory=mkdtempSync(path.join(tmpdir(),'bondtite-leads-test-'));
const env={...process.env,LEADS_DB_PATH:path.join(directory,'leads.sqlite'),LEADS_BACKUP_DIR:path.join(directory,'backups'),NEXT_BUILD_DIR:'.next-leads-test',LEADS_TRUST_PROXY:'false',LEADS_PUBLIC_ORIGIN:'http://localhost:3104'};
const origin=env.LEADS_PUBLIC_ORIGIN,password=randomUUID()+randomUUID();
execFileSync(process.execPath,['scripts/leads-admin.mjs','set-password','tester'],{env,input:password,stdio:['pipe','pipe','pipe']});
const child=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--port','3104'],{env,stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);
const request=(url,body,headers={})=>fetch(origin+url,{method:'POST',redirect:'manual',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
let database;
try{
  let ready=false;for(let i=0;i<90;i++){if(child.exitCode!==null)throw new Error('Server exited: '+output);try{const res=await fetch(origin+'/admin/leads');if(res.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}
  assert.ok(ready,'Server ready');database=new DatabaseSync(env.LEADS_DB_PATH);
  const base={name:'Backend test',source_page:origin+'/contact?project=private-details#form',mobile:'9999999901',email:'test@example.invalid',topic:'Product selection',message:'=HYPERLINK("bad")',consent:true};
  assert.equal((await request('/api/leads',base,{Origin:'https://foreign.invalid'})).status,403);
  assert.equal((await request('/api/leads',{...base,consent:false})).status,400);
  assert.equal((await request('/api/leads',{...base,website:'spam'})).status,400);
  assert.equal((await request('/api/leads',{...base,message:'x'.repeat(13000)})).status,413);
  assert.equal((await request('/api/leads',{...base,mobile:'0000000000'})).status,400);
  assert.equal((await request('/api/tds',{name:'Placeholder test',mobile:'0000000000',product:'bondtite-hydra',consent:true})).status,400);
  const key=randomUUID();
  const a=await request('/api/leads',base,{'Idempotency-Key':key});assert.equal(a.status,201);const {id}=await a.json();
  const attribution=database.prepare('SELECT source_page,form_name,created_at FROM leads WHERE id=?').get(id);
  assert.equal(attribution.source_page,origin+'/contact');assert.equal(attribution.form_name,'Contact form');assert.ok(Number.isFinite(Date.parse(attribution.created_at)));
  const b=await request('/api/leads',base,{'Idempotency-Key':key});assert.equal((await b.json()).id,id);
  const simultaneous=await Promise.all([request('/api/leads',base,{'Idempotency-Key':randomUUID()}),request('/api/leads',base,{'Idempotency-Key':randomUUID()})]);
  for(const response of simultaneous)assert.equal((await response.json()).id,id);
  assert.equal(database.prepare('SELECT count(*) AS n FROM leads').get().n,1);
  assert.equal((await request('/api/leads',{...base,message:'Different'}, {'Idempotency-Key':key})).status,409);
  const tds={name:'Document test',source_page:origin+'/products/woodworking/bondtite-hydra',mobile:'9999999902',product:'bondtite-hydra',consent:true};
  const pdf=await request('/api/tds',tds,{'Idempotency-Key':randomUUID()});assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');
  assert.equal(database.prepare("SELECT count(*) AS n FROM leads WHERE source='tds'").get().n,1);
  const tdsOrigin=database.prepare("SELECT source_page,form_name FROM leads WHERE source='tds'").get();assert.equal(tdsOrigin.source_page,origin+'/products/woodworking/bondtite-hydra');assert.equal(tdsOrigin.form_name,'TDS download form');
  // Every registered document saves its own product and returns its own PDF.
  const manifest=readFileSync('lib/documents.ts','utf8');
  const docs=JSON.parse(manifest.slice(manifest.indexOf('= ')+2,manifest.indexOf(';\nexport')));
  let documentIndex=0;
  for(const [slug,document] of Object.entries(docs)) {
    const mobile=String(9876500000+documentIndex++);
    const result=await request('/api/tds',{...tds,mobile,product:slug,source_page:origin+'/products/test/'+slug},{'Idempotency-Key':randomUUID()});
    assert.equal(result.status,200,slug);
    assert.deepEqual(Buffer.from(await result.arrayBuffer()),readFileSync(path.join('private/documents',document.file)),slug+' exact PDF');
    assert.ok(result.headers.get('content-disposition').includes(document.file));
    const lead=database.prepare('SELECT product,source_page FROM leads WHERE mobile=?').get(mobile);
    assert.equal(lead.source_page,origin+'/products/test/'+slug);
    assert.ok(lead.product && (slug==='bondtite-hydra'||lead.product!=='Hydra+'));
  }
  for(const product of ['__proto__','constructor','../../secret','unlisted'])assert.equal((await request('/api/tds',{...tds,product},{'Idempotency-Key':randomUUID()})).status,400);
  assert.equal((await fetch(origin+'/api/admin/leads/export')).status,401);
  const login=await fetch(origin+'/api/admin/login',{method:'POST',redirect:'manual',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({username:'tester',password})});
  assert.equal(login.status,303);const cookie=login.headers.get('set-cookie').split(';')[0];
  const auth={Cookie:cookie,Origin:origin,'Content-Type':'application/x-www-form-urlencoded'};
  const update={id,status:'qualified',notes:'Follow up tomorrow',assignee:'tester',follow_up:'2026-10-01',version:'0'};
  assert.equal((await fetch(origin+'/api/admin/leads',{method:'POST',headers:{Origin:origin},body:new URLSearchParams(update)})).status,401);
  assert.equal((await fetch(origin+'/api/admin/leads',{method:'POST',redirect:'manual',headers:auth,body:new URLSearchParams(update)})).status,303);
  assert.equal((await fetch(origin+'/api/admin/leads',{method:'POST',redirect:'manual',headers:auth,body:new URLSearchParams(update)})).status,409);
  assert.equal(database.prepare('SELECT status FROM leads WHERE id=?').get(id).status,'qualified');
  assert.equal(database.prepare("SELECT actor FROM lead_audit WHERE lead_id=? AND action='updated'").get(id).actor,'tester');
  const csv=await fetch(origin+'/api/admin/leads/export',{headers:{Cookie:cookie}});assert.equal(csv.status,200);const exported=await csv.text();assert.ok(exported.includes("'=HYPERLINK"),'CSV formula neutralized');assert.ok(exported.includes('source_page'));assert.ok(exported.includes(origin+'/contact'));
  const inbox=await fetch(origin+'/admin/leads',{headers:{Cookie:cookie}});assert.ok((await inbox.text()).includes('Activity history'));
  database.exec("CREATE TRIGGER simulate_failure BEFORE INSERT ON leads BEGIN SELECT RAISE(FAIL, 'test unavailable'); END;");
  assert.equal((await request('/api/leads',{...base,mobile:'9999999903',message:'Failure test'})).status,503);
  database.exec('DROP TRIGGER simulate_failure');
  assert.equal(database.prepare("SELECT count(*) AS n FROM leads WHERE mobile='9999999903'").get().n,0);
  const spam={...base,mobile:'9999999904'};let last;
  for(let i=0;i<9;i++)last=await request('/api/leads',{...spam,message:'Spam '+i});assert.equal(last.status,429);
  const backupOutput=execFileSync(process.execPath,['scripts/leads-backup.mjs'],{env,encoding:'utf8'});
  const backupFile=JSON.parse(backupOutput.trim()).file,restored=path.join(directory,'restored.sqlite');
  execFileSync(process.execPath,['scripts/leads-restore.mjs',backupFile,restored],{env,stdio:'pipe'});
  const copy=new DatabaseSync(restored);assert.equal(copy.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(copy.prepare('SELECT count(*) AS n FROM leads').get().n,database.prepare('SELECT count(*) AS n FROM leads').get().n);assert.equal(copy.prepare('SELECT count(*) AS n FROM admin_sessions').get().n,0);copy.close();
  assert.ok(readFileSync(backupFile+'.sha256','utf8').trim());
  await fetch(origin+'/api/admin/logout',{method:'POST',redirect:'manual',headers:auth});
  assert.equal((await fetch(origin+'/api/admin/leads/export',{headers:{Cookie:cookie}})).status,401);
  console.log('PASS: validation, origin checks, honeypot, size limit, concurrent deduplication, key conflicts, TDS, authentication, audit, stale edits, safe CSV, storage failures, throttling, backup/restore, session revocation.');
}catch(error){console.error(output.slice(-2500));throw error;}finally{database?.close();child.kill('SIGTERM');await new Promise(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',resolve);});rmSync(directory,{recursive:true,force:true});}
